#!/bin/bash
# mod2mp3 - converts MOD files to MP3 format, based on FFMPEG

INPUT_FILE="$1"
OUTPUT_FILE="`echo $INPUT_FILE | sed -e s/.mod/.mp3/g`"

ffmpeg -i $INPUT_FILE -acodec mp3 -ab 192k -ar 48000 $OUTPUT_FILE
